HousingSearchListener.Tests/V1/E2ETests/Steps/AddPersonToTenureSteps.cs
HousingSearchListener.Tests/V1/E2ETests/Stories/AddPersonToTenureTests.cs
HousingSearchListener.Tests/V1/UseCase/AddPersonToTenureUseCaseTests.cs
HousingSearchListener/V1/UseCase/AddPersonToTenureUseCase.cs

https://hackney.atlassian.net/browse/MTTL-1523.
Ensure person details are updated with the tenure info for the PersonAddedToTenure event processing _if_ the person details retrieved from the person api have not yet been updated.

Added missing functionality

---

HousingSearchListener/serverless.yml

Use the T&L Accounts API token to avoid conflicts with MTFH: Finance

Amend Account API Token path

---

HousingSearchListener.Tests/V1/E2ETests/Steps/UpdateAccountDetailsSteps.cs
HousingSearchListener.Tests/V1/E2ETests/Stories/UpdateAccountDetailsTests.cs
HousingSearchListener/V1/Boundary/EventTypes.cs
HousingSearchListener/V1/Factories/UseCaseFactory.cs
HousingSearchListener/V1/UseCase/UpdateAccountDetailsUseCase.cs

https://app.clickup.com/t/1kck3df
Update housing search listener to listen the AccountCreatedEvent and AccountUpdatedEvent to update totalBalance for Person tenures

Add logic to update person balance

---

HousingSearchListener.Tests/HousingSearchListener.Tests.csproj
HousingSearchListener.Tests/V1/E2ETests/Fixtures/ContractApiFixture .cs
HousingSearchListener.Tests/V1/E2ETests/Steps/AddAssetToIndexSteps.cs
HousingSearchListener.Tests/V1/E2ETests/Steps/AddProcessToIndexSteps.cs
HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
HousingSearchListener.Tests/V1/Gateway/AssetApiGatewayTests.cs
HousingSearchListener.Tests/V1/UseCase/IndexCreateAssetUseCaseTests.cs
HousingSearchListener.Tests/V1/UseCase/IndexProcessUseCaseTests.cs
HousingSearchListener.Tests/V1/UseCase/UpdateAssetUseCaseTests.cs
HousingSearchListener/HousingSearchListener.csproj
HousingSearchListener/V1/Factories/ESEntityFactory.cs
HousingSearchListener/V1/Factories/IESEntityFactory.cs
HousingSearchListener/V1/Gateway/AssetApiGateway.cs
HousingSearchListener/V1/Gateway/ContractApiGateway.cs
HousingSearchListener/V1/Gateway/Interfaces/IAssetApiGateway.cs
HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs
HousingSearchListener/V1/UseCase/IndexCreateAssetUseCase.cs
HousingSearchListener/V1/UseCase/IndexProcessUseCase.cs
HousingSearchListener/V1/UseCase/UpdateAssetUseCase.cs

MR-698 - https://hackney.atlassian.net/jira/software/c/projects/MR/boards/88?modal=detail&selectedIssue=MR-698
Given the recent update to Hackney.Asset.Shared to v 0.30, we have been reviewing all solutions that use this library and make any adjustments if necessary.
- Removed Hackney.Asset.Shared package from dependencies as it's not in use
- Removed unnecessary usings from files where Hackney.Asset.Shared was listed as an "import", despite not being in use.
Properties within the AssetDb class (within Hackney.Asset.Shared) of type 'int' and 'boolean' have been set from non-nullable to nullable with the latest update of the library, to version 0.30.

Removed Hackney.Asset.Shared package from dependencies as it's not in use

---

HousingSearchListener.Tests/ElasticSearchFixture.cs
HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
HousingSearchListener.Tests/data/indexes/tenureIndex.json
HousingSearchListener/HousingSearchListener.csproj
HousingSearchListener/V1/Domain/Tenure/TempAccommodationInfo.cs
HousingSearchListener/V1/Domain/Tenure/TemporaryAccommodationInfo.cs
HousingSearchListener/V1/Domain/Tenure/TenureInformation.cs
HousingSearchListener/V1/Factories/ESEntityFactory.cs

[TS-1389](https://hackney.atlassian.net/browse/TS-1389)
We are working on new worktray feature for temporary accommodation officers in the Book Temporary Accommodation app. The worktray is powered by the tenure index in the housing search that this listener maintains. Currently we are not storing the booking status to the tenure index, so it's not available to clients. 
`QueryableTenure` model in the `Hackney.Shared.HousingSearch` package has been updated ([PR](https://github.com/LBHackney-IT/housing-search-shared/pull/73)) to include `QueryableTempAccommodationInfo` which includes the booking status details and this change implements the updated property by including it in to the tenure index to make it available for clients. It's worth noting that the `TempAccommodationInfo` object will …

TS-1389 Add temporary accommodation booking status to tenure

---

HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
HousingSearchListener.Tests/data/indexes/tenureIndex.json
HousingSearchListener/HousingSearchListener.csproj
HousingSearchListener/V1/Domain/Tenure/TempAccommodationInfo.cs
HousingSearchListener/V1/Domain/Tenure/TempAccommodationOfficer.cs
HousingSearchListener/V1/Domain/Tenure/TenuredAsset.cs
HousingSearchListener/V1/Factories/ESEntityFactory.cs

[TS-1403](https://hackney.atlassian.net/browse/TS-1403)
We are working on new worktray feature for temporary accommodation officers in the Book Temporary Accommodation app. The worktray is powered by the tenure index in the housing search that this listener maintains. Currently we are not storing the assigned officer details for the booking in the tenure index, so it's not available to clients. 
Update the `TempAccommodationInfo` object with new `AssignedOfficer` property and update the `CreateQueryableTenure` method to store the officer details to the tenure index object.
Add additional test to verify the `QueryableTenure` object shape when TA details are not provided.
Update the `Hackney.Shared.HousingSearch` package to 0.71.0 which includes the assigned officer details. ([related PR …

TS-1403 add assigned officer support for TA

---

HousingSearchListener.Tests/data/indexes/tenureIndex.json
HousingSearchListener/HousingSearchListener.csproj
HousingSearchListener/V1/Domain/Tenure/TempAccommodationInfo.cs
HousingSearchListener/V1/Domain/Tenure/TempAccommodationOfficer.cs
HousingSearchListener/V1/Domain/Tenure/TenureInformation.cs
HousingSearchListener/V1/Factories/ESEntityFactory.cs

[TS-1406](https://hackney.atlassian.net/browse/TS-1406)
Current `TempAccommodationOfficer` model in the shared search package does not have Id in it, so we can't use the Ids on the front end to identify officers.
1. Update the `Hackney.Shared.HousingSearch` package to version 0.72.0 which adds the officer id support.
2. Remove `TempAccommodationInfo` and `TempAccommodationOfficer` domain models and use the ones from the shared package instead. There's no value duplicating objects in this use case, so to simplify things they have been removed
None
[TS-1406]: https://hackney.atlassian.net/browse/TS-1406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TS-1406 add assigned officer id support for temporary accommodation

---

HousingSearchListener/HousingSearchListener.csproj

This PR updates the housing search shared package to the latest 0.73.0.
To introduce the new nullable fields from this [PR](https://github.com/LBHackney-IT/housing-search-shared/pull/77)

Update shared package to 0.73.0

---

.circleci/config.yml

Title says all.
To resolve a deployment issue relating to using serverless V4 and to continue to deploy without a licence.

Pin serverless version to v3

---

HousingSearchListener.Tests/V1/E2ETests/Fixtures/ContractApiFixture .cs
HousingSearchListener.Tests/V1/E2ETests/Steps/AddOrUpdateContractOnAssetTestsSteps.cs
HousingSearchListener.Tests/V1/E2ETests/Stories/AddOrUpdateContractOnAssetTests.cs
HousingSearchListener/HousingSearchListener.csproj
HousingSearchListener/V1/Factories/ESEntityFactory.cs
HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs

https://hackney.atlassian.net/browse/TS-1501
TA officers need to be able to see the data about contracts alongside asset data so that they can see the data they need to make a contract approval.
This PR relates to changes required to populate the asset contract with additional fields that are to be used either for querying the contract in the case of `isApproved`, or for display purposes in the case of the other fields.
A related [change](https://github.com/LBHackney-IT/housing-search-api/pull/231) is for querying the asset data using the new `isApproved` field.
- additional fields added to `AssetContract`
- new E2E tests covering `AddOrUpdateContractInAssetUseCase`

TS-1501: Extend housing search listener to populate additional contract fields in the ES index

---

HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
HousingSearchListener/V1/Factories/ESEntityFactory.cs

[TS-1528](https://hackney.atlassian.net/browse/TS-1528)
When contract is initially created against asset in Book Temporary Accommodation it won't have the related people (`Asset.AssetContract.RelatedPeople`) or charges (`Asset.AssetContract.Charges`) set against it. Listener is using the same use case for creating and updating a contract for asset and expects them to be in place from the first creation.
However in BTA app those values will never be initially populated when the listener handles the first `ContractCreated` event, so the current implementation causes an exception to be thrown and the update not getting added to the `assets` index.
Add null checks for both `RelatedPeople` and `Charges` to ensure the index is updated with the rest of the values regardles of whether those two …

TS-1528 Fix related people and rates handling in asset contract

---

HousingSearchListener/HousingSearchListener.csproj
HousingSearchListener/V1/Factories/ESEntityFactory.cs
HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs

https://hackney.atlassian.net/browse/TS-1528
On BTA, contracts that are inactive and not approved are being displayed on the contracts worktray. To avoid this, we need to expose whether the contract is active or not on the AssetContract subentity in the Housing Search. 
We have deployed a new package version for this to be saved ([PR here](https://github.com/LBHackney-IT/housing-search-shared/pull/80)).
This PR is for the Contract status to be picked up by the listener and put into the AssetContract, so that then we can use it as a filter. It's essentially just extending [this previous PR](https://github.com/LBHackney-IT/housing-search-listener/pull/124/) by 1 more parameter.
Updated package version and added one parameter
Following this, there will be a PR on the API as well

TS-1528: Update Contract Status to AssetContract

---

HousingSearchListener/HousingSearchListener.csproj
HousingSearchListener/V1/Factories/ESEntityFactory.cs
HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs

https://hackney.atlassian.net/browse/TS-1610
BTA users want to be able to reset the contract approval status of an updated approved contract so that it can be submitted for reapproval. This calls for changing from a boolean value to an enum in the Contracts, to account for more than two possible statuses. We need this field to be picked up bi the Listener so that we can retrieve it with the API
We haven't removed the `isApproved` flag yet so that the FE can continue to function until we introduce the new field there too.
Updated Hackney.Shared.HousingSearch package version
New field in EntityFactory and usecase.
Update the API.

TS-1610: Add new ApprovalStatus field on AssetContract

---

HousingSearchListener/HousingSearchListener.csproj
HousingSearchListener/V1/Factories/ESEntityFactory.cs
HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs

https://hackney.atlassian.net/browse/TS-1614
BTA users need a way to cancel invalid contracts (contracts opened in error) so that approval will no longer be required and no payment will be made to agent/landlord.
To do so, we need to see data about when and why a Contract was ended in the Asset information, as it will inform the decision about display a Contract for approval on BTA.
Shared package version update, factory and usecase update.
Updating the API

TS-1614: Adding data about the end of an assetContract

---

HousingSearchListener/HousingSearchListener.csproj

https://hackney.atlassian.net/browse/TS-1746
We need for ApprovalStatus to be set as a string in the Housing Search world to avoid de/serialisation issues and receive it as a string (as opposed to the current integer) in the Housing Search API response
Upgraded package version.
Update API.

TS-1746: Update shared package version to have ApprovalStatus as a string

---

HousingSearchListener.Tests/ElasticSearchFixture.cs
HousingSearchListener.Tests/FixtureConstants.cs
HousingSearchListener.Tests/V1/E2ETests/Fixtures/AssetApiFixture.cs
HousingSearchListener.Tests/V1/E2ETests/Fixtures/ContractApiFixture .cs
HousingSearchListener.Tests/V1/E2ETests/Fixtures/MultipleContractApiFixture.cs
HousingSearchListener.Tests/V1/E2ETests/Steps/AddOrUpdateContractOnAssetTestsSteps.cs
HousingSearchListener.Tests/V1/E2ETests/Steps/BaseSteps.cs
HousingSearchListener.Tests/V1/E2ETests/Stories/AddOrUpdateContractOnAssetTests.cs
HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
HousingSearchListener.Tests/V1/UseCase/AddOrUpdateContractInAssetUseCaseTests.cs
HousingSearchListener.Tests/V1/UseCase/IndexCreateAssetUseCaseTests.cs
HousingSearchListener.Tests/V1/UseCase/UpdateAssetUseCaseTests.cs
HousingSearchListener/HousingSearchListener.csproj
HousingSearchListener/V1/Factories/ESEntityFactory.cs
HousingSearchListener/V1/Gateway/ContractApiGateway.cs
HousingSearchListener/V1/Gateway/Interfaces/IContractApiGateway.cs
HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs

https://hackney.atlassian.net/browse/TS-1631
On BTA, the Contracts approval Worktray relies on the Housing Search system to display what contract belongs to which asset. Currently, only the latest contract is saved by the Listener, however, in some instances, BTA users will need to approve more than one contract on the same property. This happens, for example, if a tenant moves in and out of the property in a matter of days: since the contract approval is not guaranteed to be done on a daily basis, those contracts would not be approved in time.
This PR follows the one on the shared package found [here](https://github.com/LBHackney-IT/housing-search-shared/pull/89).
The changes in this and the following API PR will move `AssetContract ` property on the `Asset `entity from a single one to a …

TS-1631: Display multiple pending contracts for the same property

---

HousingSearchListener.Tests/V1/E2ETests/Stories/AddOrUpdateContractOnAssetTests.cs
HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs

https://hackney.atlassian.net/browse/TS-1631
This PR partially reverts the [previous one](https://github.com/LBHackney-IT/housing-search-listener/pull/137), where we were operating on the assumption the SNS message would contain the assetId. As it turns out, this is not the case. So we're going back to obtaining the assetId from the contract itself. The rest of the logic is unchanged from the previous PR.

TS-1631 - Return to retrieving assetId from contract

---

HousingSearchListener.Tests/V1/E2ETests/Fixtures/MultipleContractApiFixture.cs
HousingSearchListener.Tests/V1/E2ETests/Stories/AddOrUpdateContractOnAssetTests.cs
HousingSearchListener.Tests/V1/UseCase/AddOrUpdateContractInAssetUseCaseTests.cs
HousingSearchListener/V1/Gateway/ContractApiGateway.cs
HousingSearchListener/V1/Gateway/Interfaces/IContractApiGateway.cs
HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs

https://hackney.atlassian.net/browse/TS-1631
When we are retrieving multiple contracts from the dedicated endpoint on the Contract API, those results are paged, something I (sillily) hadn't taken into account. At the moment, the Listener fails when retrieving those results as it expects a list of contracts. This PR aims to remediate that.

TS-1631: AssetContracts: handle PagedResult

---

HousingSearchListener.Tests/V1/E2ETests/Fixtures/MultipleContractApiFixture.cs
HousingSearchListener.Tests/V1/E2ETests/Steps/AddOrUpdateContractOnAssetTestsSteps.cs
HousingSearchListener.Tests/V1/E2ETests/Stories/AddOrUpdateContractOnAssetTests.cs
HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs

Fix for a bug where `QueryableAssets` were not updated in the index if they did not have any no-approved contracts.
The PR looks worse than the change is due to the removal of a layer of indentation changes the formatting. The actual changes are in `AddOrUpdateContractInAssetUseCase`, and involved removing the `if (allFilteredContracts.Any())` statement and moving the  `await UpdateAssetIndexAsync(asset);` call outside the contract processing loop.
Now the asset is updated in all cases, regardless of the contracts it has.

TS-1923: Always update the asset in the index regardless of contract status

---

HousingSearchListener.Tests/V1/E2ETests/Stories/AddOrUpdateContractOnAssetTests.cs

Skip an intermittently failing test.
This test fails a proportion of the time, causing issues with builds failing. It is always the `ContractUpdatedEvent`, an not the `ContractCreatedEvent` even though there is not change of behaviour between the two event types.
Further investigation is required to fix. A ticket has been raised to cover this issue and another issue with the same set of tests.
https://hackney.atlassian.net/browse/TS-1937

Skipped E2E AddOrUpdateContractOnAssetTests test that fails intermittently

---

HousingSearchListener.Tests/V1/E2ETests/Stories/AddOrUpdateContractOnAssetTests.cs

Sadly [this PR](https://github.com/LBHackney-IT/housing-search-listener/pull/155) solved the issue of the flaky test only locally and upon deployment to dev. Merging into staging made it flake again. Rolling back to a stable version until we have the resources to investigate this properly.

TS-1937: Skipping test as it's still flaky

---

HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs

https://hackney.atlassian.net/browse/TS-2027
When we adapted the Assets to include multiple contracts (see [here](https://github.com/LBHackney-IT/housing-search-listener/pull/137/) for the main PR) we needed to ignore Approved contract.
This has now changed, as we need to carry over Approved contracts to ES too. Filtering on status is already present on the FE where needed.
Deleted unneeded Where condition in filter
None

BTA - Carry over approved contracts too
