LBHackney-IT/housing-search-listener

- .circleci/config.yml
- HousingSearchListener/V1/Domain/User.cs
https://hackney.atlassian.net/browse/MTTL-1099
Removed user id from incoming message definition
> Removed user id

- .circleci/config.yml
- CODEOWNERS
- HousingSearchListener/V1/Domain/User.cs
Release logging changes to staging
> Release mttl 1101

- HousingSearchListener.Tests/ElasticSearchFixture.cs
- HousingSearchListener.Tests/V1/E2ETests/Steps/AddTenureToIndexSteps.cs
- HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
- HousingSearchListener.Tests/V1/Gateway/EsGatewayTests.cs
- HousingSearchListener.Tests/V1/UseCase/IndexTenureUseCaseTests.cs
- HousingSearchListener/V1/Domain/ElasticSearch/QueryableHouseholdMember.cs
- HousingSearchListener/V1/Domain/ElasticSearch/QueryableTenure.cs
- HousingSearchListener/V1/Domain/ElasticSearch/QueryableTenureType.cs
- HousingSearchListener/V1/Domain/ElasticSearch/QueryableTenuredAsset.cs
- HousingSearchListener/V1/Domain/Tenure/HouseholdMembers.cs
- HousingSearchListener/V1/Domain/Tenure/TenureInformation.cs
- HousingSearchListener/V1/Factories/ESEntityFactory.cs
- HousingSearchListener/V1/Factories/IESEntityFactory.cs
- HousingSearchListener/V1/Gateway/EsGateway.cs
- HousingSearchListener/V1/Gateway/IEsGateway.cs
- HousingSearchListener/V1/UseCase/IndexTenureUseCase.cs
Corrected the data model of tenure information that gets added to ES for the new tenure event processing.
> Corrected tenure data stored in ES

- terraform/development/main.tf
- terraform/development/variables.tf
- terraform/production/main.tf
- terraform/production/variables.tf
- terraform/staging/main.tf
- terraform/staging/variables.tf
https://hackney.atlassian.net/browse/MTTL-1461
Get metrics in easy to view dashboard
CW dashboard added
> added listener cw dashboard

- .circleci/config.yml
We want to deploy to dev from al feature branches to keep Master in a working state
Removed filter to deploy to development
> changed dev deployment

- HousingSearchListener.Tests/ElasticSearchFixture.cs
- HousingSearchListener.Tests/V1/E2ETests/Fixtures/BaseApiFixture.cs
- HousingSearchListener.Tests/V1/E2ETests/Fixtures/TenureApiFixture.cs
- HousingSearchListener.Tests/V1/E2ETests/Steps/AddPersonToIndexSteps.cs
- HousingSearchListener.Tests/V1/E2ETests/Steps/AddPersonToTenureSteps.cs
- HousingSearchListener.Tests/V1/E2ETests/Steps/AddTenureToIndexSteps.cs
- HousingSearchListener.Tests/V1/E2ETests/Stories/AddPersonToIndexTests.cs
- HousingSearchListener.Tests/V1/E2ETests/Stories/AddPersonToTenureTests.cs
- HousingSearchListener.Tests/V1/E2ETests/Stories/AddTenureToIndexTests.cs
- HousingSearchListener.Tests/V1/Factories/UseCaseFactoryTests.cs
- HousingSearchListener.Tests/V1/Gateway/PersonApiGatewayTests.cs
- HousingSearchListener.Tests/V1/Gateway/TenureApiGatewayTests.cs
- HousingSearchListener.Tests/V1/UseCase/AddPersonToTenureUseCaseTests.cs
- HousingSearchListener.Tests/V1/UseCase/IndexCreatePersonUseCaseTests.cs
- HousingSearchListener.Tests/V1/UseCase/IndexTenureUseCaseTests.cs
- HousingSearchListener.Tests/V1/UseCase/IndexUpdatePersonUseCaseTests.cs
- HousingSearchListener/V1/Factories/UseCaseFactory.cs
- HousingSearchListener/V1/Gateway/IPersonApiGateway.cs
- HousingSearchListener/V1/Gateway/ITenureApiGateway.cs
- HousingSearchListener/V1/Gateway/PersonApiGateway.cs
- HousingSearchListener/V1/Gateway/TenureApiGateway.cs
- HousingSearchListener/V1/UseCase/AddPersonToTenureUseCase.cs
- HousingSearchListener/V1/UseCase/IndexCreatePersonUseCase.cs
- HousingSearchListener/V1/UseCase/IndexTenureUseCase.cs
- HousingSearchListener/V1/UseCase/IndexUpdatePersonUseCase.cs
https://hackney.atlassian.net/browse/MTTL-1620
Added x-correlation-id request header to Api calls
Also had to fix a number of tests and correct a number of (what I imagine were) previous merge errors.
> Added x-correlation-id request header to Api call

- HousingSearchListener.Tests/ElasticSearchFixture.cs
- HousingSearchListener.Tests/V1/E2ETests/Fixtures/PersonApiFixture.cs
- HousingSearchListener.Tests/V1/E2ETests/Steps/RemovePersonFromTenureSteps.cs
- HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
- HousingSearchListener.Tests/V1/UseCase/RemovePersonFromTenureUseCaseTests.cs
- HousingSearchListener/V1/Domain/Person/Person.cs
- HousingSearchListener/V1/Factories/ESEntityFactory.cs
- HousingSearchListener/V1/UseCase/AddPersonToTenureUseCase.cs
- HousingSearchListener/V1/UseCase/RemovePersonFromTenureUseCase.cs
Correct property name to fix null reference exception
> Correct property name

- HousingSearchListener.Tests/HousingSearchListener.Tests.csproj
- HousingSearchListener/HousingSearchListener.csproj
https://hackney.atlassian.net/browse/MTTL-2071
Updating the nuget package
bumping the package version to include a bug fix
> bumping the package version

- HousingSearchListener.Tests/ElasticSearchFixture.cs
- HousingSearchListener.Tests/V1/E2ETests/Steps/AddTenureToIndexSteps.cs
- HousingSearchListener.Tests/V1/E2ETests/Stories/AddTenureToIndexTests.cs
- HousingSearchListener.Tests/V1/UseCase/IndexTenureUseCaseTests.cs
- HousingSearchListener/V1/UseCase/IndexTenureUseCase.cs
https://hackney.atlassian.net/browse/MTTL-2113
Processing tenure events did not update the tenure details on any associated person records.
> Ensure person records are updated on tenure events

- .circleci/config.yml
- HousingSearchListener.Tests/ElasticSearchFixture.cs
- HousingSearchListener.Tests/FixtureConstants.cs
- HousingSearchListener.Tests/HousingSearchListener.Tests.csproj
- HousingSearchListener.Tests/V1/E2ETests/Fixtures/FinancialTransactionApiFixture.cs
- HousingSearchListener.Tests/V1/E2ETests/Steps/AddTransactionToIndexSteps.cs
- HousingSearchListener.Tests/V1/E2ETests/Stories/AddTransactionToIndexTests.cs
- HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
- HousingSearchListener.Tests/V1/Factories/UseCaseFactoryTests.cs
- HousingSearchListener.Tests/V1/Gateway/FinancialTransactionApiGatewayTests.cs
- HousingSearchListener.Tests/V1/UseCase/IndexTransactionUseCaseTests.cs
- HousingSearchListener.Tests/data/indexes/transactionIndex.json
- HousingSearchListener/HousingSearchListener.cs
- HousingSearchListener/HousingSearchListener.csproj
- HousingSearchListener/V1/Boundary/EventTypes.cs
- HousingSearchListener/V1/Domain/Transaction/Person.cs
- HousingSearchListener/V1/Domain/Transaction/TransactionResponseObject.cs
- HousingSearchListener/V1/Factories/ESEntityFactory.cs
- HousingSearchListener/V1/Factories/IESEntityFactory.cs
- HousingSearchListener/V1/Factories/UseCaseFactory.cs
- HousingSearchListener/V1/Gateway/EsGateway.cs
- HousingSearchListener/V1/Gateway/FinancialTransactionApiGateway.cs
- HousingSearchListener/V1/Gateway/IEsGateway.cs
- HousingSearchListener/V1/Gateway/IFinancialTransactionApiGateway.cs
- HousingSearchListener/V1/UseCase/IndexTransactionUseCase.cs
- HousingSearchListener/V1/UseCase/Interfaces/IIndexTransactionUseCase.cs
- HousingSearchListener/serverless.yml
Add a link to the JIRA ticket that the changes in this PR describe.
When ever there is a transaction is generated we also need to index the same in Elastic Search.
When ever there is a transaction is generated we also need to index the same in Elastic Search. We have added use case in Housing Search Listener to index Transaction in ES so that Housing Search API Transaction search endpoint will work for latest Transaction.
- [checked ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added …
> Added Transaction Indexing

- terraform/development/main.tf
Add a link to the JIRA ticket that the changes in this PR describe.
Added Subscription into TransactionSQS
Added Subscription into TransactionSQS in Terraform.
- [checked ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [checked  ] Added tests to cover all new production code
- [checked  ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ checked ] Checked all code for possible refactoring
- [ checked ] Code …
> Added Subscription into TransactionSQS

- HousingSearchListener.Tests/HousingSearchListener.Tests.csproj
- HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
- HousingSearchListener/HousingSearchListener.csproj
- HousingSearchListener/V1/Factories/ESEntityFactory.cs
https://app.clickup.com/t/1xgxp46
Update TransactionCreated handler to import new TransactionType enum values
TransactionCreated handler updated with new TransactionType enum values
> Import new transactiontype enum

- HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
- HousingSearchListener/V1/Domain/Transaction/TransactionResponseObject.cs
- HousingSearchListener/V1/Factories/ESEntityFactory.cs
https://app.clickup.com/t/1xgxjqv
Add logic to load SortCode field from transactions
logic to load SortCode field from transactions
> Add sort code field

- .circleci/config.yml
[JIRA ticket](https://hackney.atlassian.net/browse/MTTL-2385)
Removed deprecated --account flag
No account parameter in serverless.yml
> Removed deprecated --account flag

- .circleci/config.yml
- .dockerignore
- HousingSearchListener.Tests/Dockerfile
- docker-compose.yml
- sonar-project.properties
[Jira Ticket](https://hackney.atlassian.net/browse/MTTL-2792)
Sonar Cloud has applied
> Sonar Cloud

- .circleci/config.yml
- terraform/development/terraform-compliance/sns.feature
- terraform/production/terraform-compliance/sns.feature
- terraform/staging/terraform-compliance/sns.feature
[Jira Ticket](https://hackney.atlassian.net/browse/MTTL-2858)
Terraform Compliance
> terraform compliance

- HousingSearchListener.Tests/HousingSearchListener.Tests.csproj
- HousingSearchListener/HousingSearchListener.csproj
> Update Hackney.Shared.HousingSearch nuget package

- HousingSearchListener.Tests/HousingSearchListener.Tests.csproj
- HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
- HousingSearchListener/HousingSearchListener.csproj
- HousingSearchListener/V1/Factories/ESEntityFactory.cs
Update shared packages and add asset location
> Update shared packages and add asset location

- HousingSearchListener.Tests/FixtureConstants.cs
- HousingSearchListener.Tests/HousingSearchListener.Tests.csproj
- HousingSearchListener.Tests/V1/E2ETests/Fixtures/ProcessesApiFixture.cs
- HousingSearchListener.Tests/V1/E2ETests/Steps/AddProcessToIndexSteps.cs
- HousingSearchListener.Tests/V1/E2ETests/Steps/BaseSteps.cs
- HousingSearchListener.Tests/V1/E2ETests/Stories/AddProcessToIndexTests.cs
- HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
- HousingSearchListener.Tests/V1/Factories/UseCaseFactoryTests.cs
- HousingSearchListener.Tests/V1/Gateway/EsGatewayTests.cs
- HousingSearchListener.Tests/V1/Gateway/ProcessesApiGatewayTests.cs
- HousingSearchListener.Tests/V1/UseCase/IndexProcessUseCaseTests.cs
- HousingSearchListener/HousingSearchListener.cs
- HousingSearchListener/HousingSearchListener.csproj
- HousingSearchListener/V1/Boundary/EventTypes.cs
- HousingSearchListener/V1/Factories/ESEntityFactory.cs
- HousingSearchListener/V1/Factories/IESEntityFactory.cs
- HousingSearchListener/V1/Factories/UseCaseFactory.cs
- HousingSearchListener/V1/Gateway/EsGateway.cs
- HousingSearchListener/V1/Gateway/Interfaces/IEsGateway.cs
- HousingSearchListener/V1/Gateway/Interfaces/IProcessesApiGateway.cs
- HousingSearchListener/V1/Gateway/ProcessesApiGateway.cs
- HousingSearchListener/V1/UseCase/IndexProcessUseCase.cs
- HousingSearchListener/V1/UseCase/Interfaces/IIndexProcessUseCase.cs
- HousingSearchListener/serverless.yml
- terraform/development/main.tf
- terraform/production/main.tf
- terraform/staging/main.tf
https://hackney.atlassian.net/browse/MTTL-3104
Handle ProcessCreated events to index data for MMH's worktray correctly. 
To do: Update package from preview version once this pr is merged: https://github.com/LBHackney-IT/housing-search-shared/pull/42
> Mttl 3104: Handle ProcessCreated events

- HousingSearchListener/HousingSearchListener.cs
> Inject IContractApiGateway in startup

- HousingSearchListener.Tests/HousingSearchListener.Tests.csproj
- HousingSearchListener.Tests/V1/E2ETests/Fixtures/AssetApiFixture.cs
- HousingSearchListener.Tests/V1/E2ETests/Steps/AddAssetToIndexSteps.cs
- HousingSearchListener.Tests/V1/E2ETests/Steps/AddProcessToIndexSteps.cs
- HousingSearchListener.Tests/V1/E2ETests/Stories/UpdateAssetTests.cs
- HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
- HousingSearchListener.Tests/V1/Gateway/AssetApiGatewayTests.cs
- HousingSearchListener.Tests/V1/UseCase/AddOrUpdateContractInAssetUseCaseTests.cs
- HousingSearchListener.Tests/V1/UseCase/IndexCreateAssetUseCaseTests.cs
- HousingSearchListener.Tests/V1/UseCase/IndexProcessUseCaseTests.cs
- HousingSearchListener.Tests/V1/UseCase/UpdateAssetUseCaseTests.cs
- HousingSearchListener.sln
- HousingSearchListener/HousingSearchListener.csproj
- HousingSearchListener/V1/Factories/ESEntityFactory.cs
- HousingSearchListener/V1/Factories/IESEntityFactory.cs
- HousingSearchListener/V1/Gateway/AssetApiGateway.cs
- HousingSearchListener/V1/Gateway/Interfaces/IAssetApiGateway.cs
- HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs
- HousingSearchListener/V1/UseCase/IndexCreateAssetUseCase.cs
- HousingSearchListener/V1/UseCase/IndexProcessUseCase.cs
- HousingSearchListener/V1/UseCase/UpdateAssetUseCase.cs
> Add extra logging

- HousingSearchListener/HousingSearchListener.csproj
Update nuget package for shared search
> Update nuget package for shared search

- HousingSearchListener/V1/Factories/ESEntityFactory.cs
- HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs
Make tenure dates nullable to fix null date .toString bug.
> Make tenure dates nullable

- HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs
> Check charges count

- HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs
Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
Add descriptions of what changes were made to address the problem and provide a solution.
> Add create new object and change count to any check

- HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs
Ensure we have the ES object before writing
> Fix listener contracts

- HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs
> Add frequency to log call

- HousingSearchListener/V1/Factories/ESEntityFactory.cs
Take string value from frequency
> Take string value from frequency

- HousingSearchListener.Tests/V1/Factories/ESEntityFactoryTests.cs
- HousingSearchListener/HousingSearchListener.csproj
- HousingSearchListener/V1/Factories/ESEntityFactory.cs
- HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs
Releasing [these change](https://github.com/LBHackney-IT/housing-search-listener/pull/127) to Staging.
> TS-1528: Release to Staging

- HousingSearchListener/HousingSearchListener.csproj
- HousingSearchListener/V1/Factories/ESEntityFactory.cs
- HousingSearchListener/V1/UseCase/AddOrUpdateContractInAssetUseCase.cs
https://hackney.atlassian.net/browse/TS-1537
BTA now needs to store the reason for which a Contract might be in PendingReapproval status.
New package version etc.
Update version on API.
> TS-1537: Add ApprovalStatusReason 

- HousingSearchListener.Tests/V1/E2ETests/Stories/AddOrUpdateContractOnAssetTests.cs
Apparently, both test are now failing randomly. Skipping.
😞
> TS-1937: Skipping two tests as they both flake for no particular reason
